### ISSUE TITLE
Could not register user with Hydro ID xxxxxxx

### ISSUE THREAD

**Issue by adrenth** [adrenth/wp-hydro-raindrop#1]
When users try to register a HydroID that's already mapped, they get a 'Could not register user with Hydro ID xxxxxxx: The user is already mapped to this application.' error. Getting to that error is an edge case, so this implementing this is optional, but it might be nice to have an 'Unregister' button in that error message that lets users unlink their ID and try again.

**Comment by KondoATH** [comment]
Hi.
I have this massage.

"Could not register user with Hydro ID xxxxxx: The given username does not exist."

So I delete the Hydro app on iOS and reinstall it. And try it with another new ID, but it failed.

WordPress 4.9.8
WP Hydro Raindrop 1.2.1
Environment Sandbox

I couldn't figure out the cause.

**Comment by adrenth** [comment]
If you are using the Sandbox environment you should use the Hydro Beta app. Please contact the Hydro team to get access to the Hudro Beta app.
