### ISSUE TITLE
The API Settings are not getting loaded

### ISSUE THREAD

**Issue by HarshRajat** [adrenth/wp-hydro-raindrop#4]
Steps to Reproduce:
1. Deleted the old plugin
2. Installed the new one and activated
3. The API settings doesn't show up

![image](https://user-images.githubusercontent.com/22663032/46291458-27f1b980-c5ac-11e8-8aee-1e6ec439abc6.png)

Investigation to follow

**Comment by adrenth** [comment]
Fixed in commit d542285da245f4127ececbde4e01b7306f02098b
