### ISSUE TITLE
Private Webpages are accessible directly and in some cases if parameters are appended to the url

### ISSUE THREAD

**Issue by HarshRajat** [adrenth/wp-hydro-raindrop#5]
Steps to reproduce:
1. Just attach any parameter to the url of private pages:
1.1 https://grabberly.com/hydro-raindrop/setup/ (redirects back) -> https://grabberly.com/hydro-raindrop/setup/?ssd
-- Should redirect to hydro mfa if user is logged in and verified
1.2 https://grabberly.com/hydro-raindrop/ (redirects back)-> https://grabberly.com/hydro-raindrop/?here (shows interface)
-- should not show interface when user has entered correct mfa
1.3 https://grabberly.com/hydro-raindrop/settings/ (shows interface even when not logged in)
-- should not show interface if user is not logged in

**Comment by HarshRajat** [comment]
On further thinking, the admins should also follow the same logic, its a bit confusing for them to be bought back to hydroID page (after they setup it correctly). they can always reset and try the hydroID page for css revamp

**Comment by adrenth** [comment]
OK, I will remove this logic.

**Comment by adrenth** [comment]
See commit 91dbe24. Close it now.
